#
#spring.datasource.url=jdbc:mysql://localhost:3306/userservice
#spring.datasource.username=root
#spring.datasource.password=123

spring:
  application:
    name: postgres

  datasource:
    password: 1
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always


  main:
    allow-bean-definition-overriding: true

#  web:
#    resources:
#      static-locations: classpath:/resources/images


server:
  port: 4040

